addons:
  apt:
    packages:
    - docker-ce

env:
  global:
  - secure: Wnt31djdwWpuUsYQcUKyazhawQdJRC3cIDt8adjgMnzz8XW4zJVeUmsc43guh1LypIbbs6QEV8IFJLVhXuVddjlENUM4WA90vkqMiy+RZTXwb4vyR6Eino9QbaCVMboO4DANhs8AXi6CIEWfk82NRmQrjpGyjTiGwlNpiQAol5WTv9u/A7qlLyp6uo+ci0zLM3Z8wK/YCRGKK6O7GEIalinkCmTvoAZ40te1K3KL5PmDNN3DGg4hOVAeXzwz5rc//kke+KiqMjV9DHxtCNMH/hM7XO/zFxxifa67o3mI4TrYsU157yM2Ti0jrY/Dbhwy3ILZgVsOW8thajzfzormIUwzg3Um0nnEi8AlP22zsdHWaHXAs/F5hPCQPw1kC8gWYPGLqehPQp8aYxrAN8ZbG7UYj4giFRu2N2V6+dISCp4QMmcrsxAFsx3w7Ni0jq01JC9lH1KWewEsK/CABlCJruIuieSHX4SPe7wI70NNH7FhlAwTGxC14BoHGkZxjhScxwUsdtavqYee/VKxXd7/SE/HLwbRURda90LZDCgM58rR/s+oSY1exAccmFt2KzXQViBGbXbuWp2y9NAiODyKoY39M58QjHbz0YTN+E3yZpnQ3gZCC9kRXsayIQLwgeA7FEc2lTpXWmqlHJW51X0o/f+A+dQxhTmKrzkx3tKj8tM=
  - secure: jWdu3XLN6L4rNNpCSi9lazHZ4k3QmtuNIc6Fpe7iJnYVHztAyUy9rDa13kXom0qBut4cqEsUFezty9FNne03hlW3ivx3JXJtRv6eTR/LXKHw8u3B9KWQVOYMDyAaxvmFEVQmyJm+2L59DZQijc1ZiEF+K2ESQPriXZHDyaIj2fjoxl3fgV8Je94YKsA3fjqpphQcf2wgFcB5bwJ+VWDXEbGSNWP7wvVgHaYndeFv2ryow4n5qo9gciUeamLcDel3klq45CbGR3cT8mKrS1nrDs0zfm9S1fgAMvSc3sLpyCGxOkZyNDJTR14ANulTp3KZ4hICEehh3kO0IWtqSS79SZKa1uTRqJWTntYooRE7XC0ni+gMjqI5B61lpSjzz/0X7u84JvlZOXOlIoTsiMh3J4cmf8aleXZxSd/9dCkqEPkXQcEKwFsLdJHzCO1FNJxEskM5pAMPjAKtK2V6bmpM4a38hQAO3ne+M6usKGFG2VPFLrKGsqaBk6xWFEGsuCKkNMUTy1heBZXOp9ZaNf9NxiHn4O5c52oJKtdSCV4zHcQbnjDx3b0SDuxzSLWyfhVMaSA2bq3nMmly6OPTonSoRaJx//fTKPNductbgpdUdD9na2nazwoZo6lppsY3AAiOi/LSoB87ejMTcsAq1NG5LIB8Ft8LbxECBkjgaaFP8ls=
script:
  - cp .env.example .env
  - docker-compose up -d
  - docker-compose exec web python3 manage.py test apps
  - docker-compose down

