addons:
  apt:
    packages:
    - docker-ce
script:
- cp .env.example .env
- docker-compose up -d
- docker-compose exec web python3 manage.py test apps
- docker-compose down
deploy:
  provider: heroku
  app: vibely-udl
  skip_cleanup: true
  on:
    repo: quimpm/web_project
    branch: master
  api_key:
    secure: 4zUROldPCRtmNufKb0Ph5h3Ap5yMAoW6QzWbTh7GV1PvcmlOO76fqSTfwwZgHkETGGt2P/8vh0rg4BsXBtPaCsh7OUOj28HmuKB25YfD2xTjz/O0fJw6IV6p6RgRyZXiNFgOGGjnsjmSvfzCOkndqFF/w60tuNJbT4Jp337hG07HnBGAH/aog5uX+E8X8/ZHTGgKQmT9b9iFR4pV8NpL8eMwJ+Yb3aXKwAYnSLk7eu1QBXgiIQF/6Pdy7t+8/mVtZi7afDx3akEJ+I9/e08reTKxyubt2+aPeZV09Wm/CLBs9uajphw/7WZSAWHo3Bg31zViTTF4o+hFWdXhAJBVkp8Xe9hMbXID9tojy5GmZ5LjXvIkW0pIa1K58sMnJWnqNlB949pWEvzUO4k34fOGSYFqQg8+fZmE79A7Rt0CJWZN93S3sEccFH6pO9yTetBlZ2ova0o6546ESmukxDPw995dNFYhOURk5mMVdN6CZTzIpoyNsuJLWfkm3yj5v6XlKwZteR7eq2oAMmo0KYs5ytHi36ORb3IahybBPzGX9MNR7xl0NFMWU/wGcqqjGzJM1vRF/qb7M4i0dFciF5zZ9MOPIRQKCre57kITOn1TpmkbwLhbERsjxyJn8w1WOWC3PDoX98iWNS8WhRiU0DtyYDnvS2L3MsW3jhvb1mt0cEs=
