addons:
  apt:
    packages:
    - docker-ce
script:
- cp .env.example .env
- docker-compose up -d
- docker-compose exec web python3 manage.py test apps
- docker-compose down
deploy:
  provider: heroku
  app: vibely-udl
  skip_cleanup: true
  on:
    repo: quimpm/web_project
    branch: feature/ci
  api_key:
    secure: 4zUROldPCRtmNufKb0Ph5h3Ap5yMAoW6QzWbTh7GV1PvcmlOO76fqSTfwwZgHkETGGt2P/8vh0rg4BsXBtPaCsh7OUOj28HmuKB25YfD2xTjz/O0fJw6IV6p6RgRyZXiNFgOGGjnsjmSvfzCOkndqFF/w60tuNJbT4Jp337hG07HnBGAH/aog5uX+E8X8/ZHTGgKQmT9b9iFR4pV8NpL8eMwJ+Yb3aXKwAYnSLk7eu1QBXgiIQF/6Pdy7t+8/mVtZi7afDx3akEJ+I9/e08reTKxyubt2+aPeZV09Wm/CLBs9uajphw/7WZSAWHo3Bg31zViTTF4o+hFWdXhAJBVkp8Xe9hMbXID9tojy5GmZ5LjXvIkW0pIa1K58sMnJWnqNlB949pWEvzUO4k34fOGSYFqQg8+fZmE79A7Rt0CJWZN93S3sEccFH6pO9yTetBlZ2ova0o6546ESmukxDPw995dNFYhOURk5mMVdN6CZTzIpoyNsuJLWfkm3yj5v6XlKwZteR7eq2oAMmo0KYs5ytHi36ORb3IahybBPzGX9MNR7xl0NFMWU/wGcqqjGzJM1vRF/qb7M4i0dFciF5zZ9MOPIRQKCre57kITOn1TpmkbwLhbERsjxyJn8w1WOWC3PDoX98iWNS8WhRiU0DtyYDnvS2L3MsW3jhvb1mt0cEs=
env:
  global:
    secure: b6hUT0F6+BKKdaNhLVEb6YRDU9zogxBTzprDIFjEb+aVKkLNOOJZg4aN6voY5e0wDBGMXmha/hlj5HlcJj/VK3j3GRBVfrlkcpWmZGbcpMCNC7aH6jIl2zudrqwB5BdCjk+XkkFiGRyEbhKb+oDy1JUuEQ8BSVi6QJ38bMc63Tef3K3SUrChuUwpUZx0j0R7wgkZt+zoxyHoOpdb2VGL8dBlS1Ib1BSuVXJdfeYYl8B/2srlEfP6LpqAXc0fBfHosCVe+6tbBtGUy1QLK4DQPtrKI/h5slvndn1fpdc1NOTRxgbBBvGPoNbetv182LffFZ+eauQhFcSYw9orWjzqkm0c00YnkZusvQbILiGY9hx82QIFlCBx4tprzD9W8TAIlWrsWPAEFej1DJsRYtKXT4G7bOTrlVtoH4PlvoHTJ5x+2tDlVi261aHJwmAgchMC9iLhUplIH9nWZ9KtKC5rQKAhRy7emWO9d10C7kUgANfvFC1/5bxxMxObCLfu1epTM1rjQoV67favtZ2tQnneEk0uwRZ/Nz/NZao/G4oXqx7pCdR3wURfAJt5WRyG33U5c+0ct0/jM6vPuA7Eq7XDbA5/vEntlHyEOYrCfJJn96auMcTITXi8bEmc21+PG4oPZOXZbZOj5i7CSVVQSWX2f35p+Ez492uu9NqD1zR0UaU=
