addons:
  apt:
    packages:
    - docker-ce
script:
- cp .env.example .env
- docker-compose up -d
- docker-compose exec web python3 manage.py test apps
- docker-compose down
deploy:
  provider: heroku
  app: vibely-udl
  skip_cleanup: true
  on:
    repo: quimpm/web_project
    branch: master
  api_key:
    secure: nkA64fegQqTvV6ED4o69HFjOZgl4nBnAq9kibYMjp+IpmaEOuJrVW3+LM0kAJCLyegN+oly7p3v9Km8zIbtkF2cI82XEsfCdz8UjvPD5hjdjKFvlm1lX/LAKJRhawuS4GI6AGkeukCsx1GSl28xoOHecNUJEB5aSWyfHQ4Nl728OCMqBHwDuIvP/86qhH10E5NhObY/0e1nsm9TIwr/BkcH/ADpuSdcSqZZcsNmMed0gL0D4UxKDOFVXvWQ8DXCVZcd6ZA6Dwv4gche3ufpIXkH0bdCiaMznW7/iBXSyID5GJ6QPur1MBVAxY99yAocs9pQy76N48LKU8Fol15SakReEulsfk4msLyoO/uWGmnniLl5XTTYg9aIXaJlqH12J9cHmVr8LEyUPx9I76LYjyYkeNnDQc2NLG74QYAyjdN+7zTQEvjskuek1AmDpwj1hB7VSayfDKaHV84K0TRooVtxwHqmoFVdbz5rhrEucTH33a3GlBKkaVXk8Dh/iRO1CDp1Ue02yJkAD9hK/OgDUplstR+YERNI81JVSGoK9OtSBWsSScJUZwjv7D31JCr79O2od6kHqVDd9OMGYHpprTW2j+TocF5SCw94wRxEKRLXUwPBjUiAa1pABWsH5twjDlWsUT6PVo9/X3+jRLMB3W7mwCLiKligsbGawrTyIGeQ=
