addons:
  apt:
    packages:
    - docker-ce
script:
- cp .env.example .env
- docker-compose up -d
- docker-compose exec web python3 manage.py test apps
- docker-compose down
deploy:
  provider: heroku
  app: vibely-udl
  skip_cleanup: true
  on:
    repo: quimpm/web_project
    branch: master
  api_key:
    secure: M9Vv9zfEAnlz1W3SQdIfLJ5BvI3rIjj0paTc7X/FCOUYudl6ti5jM3AOpO4ZZyImKQ0TKSjFLBimueU1qHNtXCuesg9fBF/yOfULVSKt/cSDIpBjGSlxFMEkjEY9rRWa2zMHEnIfkLZmg7TUQPfTUFGtYSq4gwuSpbVT1XPdn4438xy19DungcBo7BdK6U7GccTCGrVugHmrWP7vnTywt8jzH0fCsmF7vNNUjBJ+ogmLW1Lw2E1LgNQuCfKQHRMR/qi9Bk9uJWQDnbDLfc1X5oRzmNg2puU1rzOjnX/FdYa5hWI0vMOl17kdFD7i3Fo5gsmYSwUFUEddKXqJfOAS/aW4ewLoYTETBSG1hguM85ltt/dT1pzX0glW+AATxWpP3Q0WBIVlMrGFdXR3sv/VpEq7M7pIvHiVUL/+lcjhhHXPG+ldZ7yQqBIstuSrxAvAtmB312XHlxpLG/LDk0Ff1Q5D3E3Ed5Wq3VZ7oQh9dUbyped6zCudXug+JASjowua8AhwL0vA9WcUKc6Wkp7rqvMgEV2XSXE1jSqhphuPMjFsFd2QkdfIWKknidD1I+m/0l7mHaIOkhFrd3hgtEwPaeZRUbbLAOZQ/hUHjlyXSkvTmO9dGdi6Ui9BZjF1+7UHN6GkU5XEMMCEgp+Oku4R1IzCi8DL0NTDlhdKdCTMtKI=
