# Generated by Django 3.0.6 on 2020-05-09 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the band')),
                ('web_link', models.URLField(max_length=255, verbose_name='Web Link to Portfolio')),
                ('playlist', models.URLField(max_length=300, verbose_name='SoundCloud Playlist')),
                ('email', models.CharField(max_length=100, verbose_name='A contact email')),
                ('mobile', models.CharField(max_length=16, verbose_name='A mobile phone to contact you')),
                ('image', models.ImageField(blank=True, upload_to='img/', verbose_name='An image of the band')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('band_owner', 'User is the owner of the band')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Name of the Event')),
                ('state', models.CharField(choices=[('SR', 'Searching'), ('CL', 'Closed'), ('FN', 'Finalized')], default='SR', max_length=2, verbose_name='State of the event')),
                ('date', models.DateTimeField(verbose_name='Date of the event')),
                ('description', models.TextField()),
                ('band', models.ManyToManyField(blank=True, related_name='events', to='main.Band')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('event_owner', 'User owner of the establishment owner of the Event')],
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Establishment name')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('email', models.CharField(max_length=100, verbose_name='Email to contact you')),
                ('mobile', models.CharField(max_length=16, verbose_name='Mobile phone to contact you')),
                ('image', models.ImageField(blank=True, default=None, upload_to='img/', verbose_name='An image of the establishment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('establishment_owner', 'User owner of the establishement')],
            },
        ),
    ]
