# Generated by Django 3.0.4 on 2020-03-28 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_link', models.URLField(max_length=255)),
                ('playlist', models.URLField(max_length=300)),
                ('contacte_email', models.CharField(max_length=100)),
                ('contacte_mobil', models.CharField(max_length=16)),
                ('image', models.ImageField(default='', upload_to='img/')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('address', models.CharField(max_length=200)),
                ('contacte_email', models.CharField(max_length=100)),
                ('contacte_mobil', models.CharField(max_length=16)),
                ('image', models.ImageField(blank=True, default=None, upload_to='img/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('state', models.CharField(choices=[('SR', 'Searching'), ('CL', 'Closed'), ('FN', 'Finalized')], default='SR', max_length=2)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('band', models.ManyToManyField(blank=True, related_name='events', to='main.Band')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.Establishment')),
            ],
        ),
    ]
