# Generated by Django 3.0.5 on 2020-05-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200503_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='idUser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='establishment',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='band',
            name='contacte_email',
        ),
        migrations.RemoveField(
            model_name='band',
            name='contacte_mobil',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='contacte_email',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='contacte_mobil',
        ),
        migrations.AddField(
            model_name='band',
            name='email',
            field=models.CharField(default='a@c.com', max_length=100, verbose_name='A contact email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='mobile',
            field=models.CharField(default=3456789, max_length=16, verbose_name='A mobile phone to contact you'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establishment',
            name='email',
            field=models.CharField(default='c@a.c', max_length=100, verbose_name='Email to contact you'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establishment',
            name='mobile',
            field=models.CharField(default=234567, max_length=16, verbose_name='Mobile phone to contact you'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='band',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='An image of the band'),
        ),
        migrations.AlterField(
            model_name='band',
            name='playlist',
            field=models.URLField(max_length=300, verbose_name='SoundCloud Playlist'),
        ),
        migrations.AlterField(
            model_name='band',
            name='web_link',
            field=models.URLField(max_length=255, verbose_name='Web Link to Portfolio'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='img/', verbose_name='An image of the establishment'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Establishment name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='Date of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Name of the Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('SR', 'Searching'), ('CL', 'Closed'), ('FN', 'Finalized')], default='SR', max_length=2, verbose_name='State of the event'),
        ),
    ]
