# Generated by Django 3.0.5 on 2020-05-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200504_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='name',
            field=models.CharField(default='itacaband', max_length=255, verbose_name='Name of the band'),
            preserve_default=False,
        ),
    ]
