# Generated by Django 3.0.6 on 2020-05-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_band_name'),
        ('main', '0004_auto_20200509_1001'),
    ]

    operations = [
    ]
